# Generated by Django 5.1 on 2024-08-26 06:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blog_options_alter_comment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={},
        ),
        migrations.RenameField(
            model_name='like',
            old_name='author',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('user', 'blog')},
        ),
    ]
